### ISSUE TITLE
你好，在配置环境的时候遇到软件冲突

### ISSUE THREAD

**Issue by Jxuanrui** [Y-H-Joe/GEMINI#1]
你好，我们在配置环境到自己的服务器的时候，在运行bash install/OUTPOST_install.sh下载参考数据库的时候，出现下述软件兼容报错，请问这里应该如何修改软件配置版本？
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
eggnog-mapper 2.1.12 requires biopython==1.76, but you have biopython 1.84 which is incompatible.

**Comment by Y-H-Joe** [comment]
Hi Jxuanrui, I think this is fine. eggnog-mapper 2.1.12 is older than biopython 1.84 so it warns you about the newer version, but I think eggnog-mapper can work fine with biopython 1.84. Actually, the developer of eggnog-mapper may should update their dependency to be >= 1.76 rather than == 1.76. 
Please try to run with it, and let me know if anything else is wrong.
